config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users do
    member do
      get 'follow_users' => 'users#follow_users'
      get 'follower_users' => 'users#follower_users'
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # フォローフォロワー機能
  post 'create/:id' => 'relationships#create', as: 'follow'
  post 'destroy/:id' => 'relationships#destroy', as: 'unfollow'

  # 検索機能
  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user, optional: true
  # いいね機能
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # コメント機能
  has_many :book_comments, dependent: :destroy

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  # いいね機能
  has_many :favorites, dependent: :destroy

  # コメント機能
  has_many :book_comments, dependent: :destroy

  #フォロー・フォロワー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def create(user_id)
    follower.create(followed_id: user_id)
  end
  def destroy(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followed_user.include?(user)
  end


  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
    redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = current_user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @user = current_user
      render action: :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #非同期化の為削除　 redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #非同期化の為削除　 redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.create(params[:id])
    redirect_to request.referer
  end

  def destroy
    current_user.destroy(params[:id])
    redirect_to request.referer
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"] ["model"]
    @value = params["search"] ["value"]
    @how = params["search"] ["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model =='book'
      Book.where("title LIKE?", "%#{value}%")
    end
  end

def search_for(how, model, value)
  case how
  when 'match'
    match(model, value)
  when 'forward'
    forward(model, value)
  when 'backward'
    backward(model, value)
  when 'partical'
    partical(model, value)
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: " You have updated user successfully."
    else
      render action: :edit
    end
  end

  def follow_users
    @user = User.find(params[:id])
    @followed = @user.follower_user
  end

  def follower_users
    @user = User.find(params[:id])
    @follower = @user.followed_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<div class="comments">
  <% book.book_comments.each do |book_comment| %>
    <p>
      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <%= book_comment.created_at.strftime('%Y/%m/%d') %>
      <%= book_comment.comment %>
      <% if book_comment.user == current_user %>
        <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-sm btn-danger", "data-confirm" => "Are you sure?" do %>
        Destroy
        <% end %>
      <% end %>
    </p>
      <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
      <% end %>
</div>
<br>

app/views/book_comments/create.js.erb
$('#comments_<%= @book.id %>').html("<%= j(render: 'book_comments/comments', locals: {book: @book}) %>");

app/views/books/_newform.html.erb
      <h1 class=>New book</h1>
        <%= form_with model: book, url:'/books', local:true do |f| %>
          <h6>Title</h6>
          <%= f.text_field :title %>
          <h6>Opinion</h6>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
        <% if book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(book.errors.count, "error")%>
            prohibited this book from being saved:</h2>
              <ul>
              <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
          </div>
        <% end %>

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
            <h6>Title</h6>
              <%= f.text_field :title %>
            <h6>Opinion</h6>
              <%= f.text_area :body %>
            <h6></h6>
              <%= f.submit 'Update Book' %>
          <p>
            <%= link_to "Show", book_path(@book.id) %>
            |
            <%= link_to "Back", books_path %>
          </p>
          <% end %>

          <% if @book.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@book.errors.count, "error")%>
              prohibited this book from being saved:</h2>
                <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  　   <%= render 'users/info', user: @user %>
  　   <%= render 'books/newform', book: @book %>
  　 </div>

     <div class="col-md-8 offset-md-1">
　　  <h1>Books</h1>
　　    <table class="table">
          <thead>
           <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
             <th></th>
             <th></th>
             <th></th>
           </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
                  <% end %>
                </td>
                <td>
                  <%= link_to book.title, book_path(book.id) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td>
                  <div id="favorites_buttons_<%= book.id %>">
                    <%= render partial: 'favorites/favorite', locals: { book: book} %>
                  </div>
                </td>
                <td>
                  <%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %>
                </td>
               </tr>
            <% end %>
          </tbody>
        </table>
      </div>
　 </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @book.user %>
      <%= render 'books/newform', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <br><%= link_to @book.user.name, user_path(@book.user.id) %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book.id) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <div id="favorites_buttons_<%= @book.id %>">
                  <%= render partial: 'favorites/favorite', locals: { book: @book} %>
                </div>
              </td>
              <td>
                <p>
                  コメント件数：<%= @book.book_comments.count %>
                </p>
              </td>
              <td>
                <% if @book.user.id == current_user.id %>
                  <p><%= link_to edit_book_path(@book.id), class:"btn btn-sm btn-success" do %>
                  Edit
                    <% end %>
                  </P>
                <% end %>
              </td>
              <td>
                <% if @book.user.id == current_user.id %>
                  <p><%= link_to book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "Are you sure?" do %>
                  Destroy
                     <% end %>
                  </p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="comments">
          <%= render 'book_comments/comments', book: @book %>
        </div>
        <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], remote:true) do |f| %>
          <%= f.text_area :comment, rows: '6', cols: '80', placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ❤︎<%= book.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <main>
      <div class="container">
        <div class="row">
          <h1 class="px-3 mx-auto">
            Welcome to
              <i class="fas fa-book"></i>
            <strong>Bookers</strong>
            !
          </h1>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/homes/show.html.erb
<h1>Welcome to Bookers!</h1>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>

  <body>
    <main>
      <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
      <% end %>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcom to
              <i class="fas fa-book"></i>
              <strong>Bookers</strong>
               !!
            </h1>
            <p>
              In
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
              ,
            </p>
            <P>
              you can share and exchange opinions , inpressions , and emotions
            </P>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
              </div>
              <div class="row">
                <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/search/search.html.erb
<% if @model == 'book' %>
<h2>Books search for "<%= @value %>"</h2>
<table class= "table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <% @datas.each do |book| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<% elsif @model == 'user' %>
<h2>Users search for "<%= @value %>"</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Introduction</th>
    </tr>
  </thead>
  <% @datas.each do |user| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
  <% end %>
</table>
<% end %>

app/views/users/_info.html.erb
      <h1>User info</h1>
        <p><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></p>
          <table class="table">
            <tbody>
              <tr>
                <th>name</th>
                <th><%= user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= user.introduction %></th>
              </tr>
              <tr>
                <th>follows</th>
                <th><%= link_to user.follower.count, follower_users_user_path(user.id) %></th>
              </tr>
              <tr>
                <th>followers</th>
                <th><%= link_to user.followed.count, follow_users_user_path(user.id) %></th>
              </tr>
            </tbody>
          </table>
        <p>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", unfollow_path(user.id), method: :post, class:"btn btn-sm btn-danger" %>
            <% else %>
              <%= link_to "フォローする", follow_path(user.id), method: :post, class:"btn btn-sm btn-success" %>
            <% end %>
          <% end %>
        </p>
        <p><%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
            <% end %>
        </p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
          <label for="inputName">Name</label>
            <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
            </P>
          </div>
          <div class="form-group">
          <label for="inputImage">Image</label>
            <p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
            </p>
          </div>
          <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
            <p><%= f.text_area :introduction %>
            </p>
          </div>
          <div class="form-group">
            <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/follow_users.html.erb
<h2>Follow Users</h2>
  <table class ="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @followed.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数： #{user.follower.count}" %></td>
          <td><%= "フォロワー数： #{user.followed.count}" %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/follower_users.html.erb
<h2>Follower Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @follower.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= "フォロー数： #{user.follower.count}" %></td>
        <td><%= "フォロワー数： #{user.followed.count}" %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/newform', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>

      <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>
              <%= "フォロー数： #{user.follower.count}" %>
            </td>
            <td>
              <%= "フォロワー数： #{user.followed.count}" %>
            </td>
            <td>
              <% unless current_user == user %>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :post %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>
 </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/newform', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <% @books.each do |book| %>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <p>コメント件数：<%= book.book_comments.count %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>