config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  resources :users do
    member do
      get 'follow_users' => 'users#follow_users'
      get 'follower_users' => 'users#follower_users'
    end
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # フォローフォロワー機能
  post 'create/:id' => 'relationships#create', as: 'follow'
  post 'destroy/:id' => 'relationships#destroy', as: 'unfollow'

  # 検索機能
  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user, optional: true
  # いいね機能
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # コメント機能
  has_many :book_comments, dependent: :destroy

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  # いいね機能
  has_many :favorites, dependent: :destroy

  # コメント機能
  has_many :book_comments, dependent: :destroy

  #フォロー・フォロワー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def create(user_id)
    follower.create(followed_id: user_id)
  end
  def destroy(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followed_user.include?(user)
  end


  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = current_user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id), notice: "Book was successfully created."
    else
      @user = current_user
      render action: :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #非同期化の為削除　 redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #非同期化の為削除　 redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"] ["model"]
    @value = params["search"] ["value"]
    @how = params["search"] ["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model =='book'
      Book.where("title LIKE?", "%#{value}%")
    end
  end

def search_for(how, model, value)
  case how
  when 'match'
    match(model, value)
  when 'forward'
    forward(model, value)
  when 'backward'
    backward(model, value)
  when 'partical'
    partical(model, value)
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books

  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: " You have updated user successfully."
    else
      render action: :edit
    end
  end

  def follow_users
    @user = User.find(params[:id])
    @followed = @user.follower_user
  end

  def follower_users
    @user = User.find(params[:id])
    @follower = @user.followed_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
          <a class="navbar-brand text-white" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          </div>
    <% if user_signed_in? %>
      <ul class="nav-item">
        <%= link_to user_path(current_user) do %>
          <i class="fas fa-home"></i>Home
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to users_path do %>
          <i class="fas fa-users"></i>Users
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to books_path do %>
          <i class="fas fa-book-open"></i>Books
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>logout
        <% end %>
      </ul>
    <% else %>
      <ul class="nav-item">
        <%= link_to root_path do %>
          <i class="fas fa-home"></i>Home
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to home_about_path do %>
          <i class="fas fa-link"></i>About
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to new_user_registration_path do %>
          <i class="fas fa-user-plus"></i>sign up
        <% end %>
      </ul>
      <ul class="nav-item">
        <%= link_to new_user_session_path do %>
          <i class="fas fa-sign-in-alt"></i>login
        <% end %>
      </ul>
    <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 25px;">
        <% if user_signed_in? %>
          <%= form_with url:search_path, method: :get, local: true do |f| %>
            <%= f.text_field 'search[value]' %>
            <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
            <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical" }) %>
            <%= f.submit :"検索" %>
          <% end %>
        <% end %>
      </div>
    </div>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>